repos:
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/psf/black
    rev: 21.11b1
  - hooks:
      - id: isort
        language_version: python3
    repo: https://github.com/pycqa/isort
    rev: 5.10.1
  - hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-string-format
    repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
  - hooks:
      - id: mypy
        additional_dependencies: ["types-dataclasses>=0.6.1; python_version < '3.7'"]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
